import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  build: {
    lib: {
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        'cli/index': resolve(__dirname, 'src/cli/index.ts'),
      },
      name: 'PromptsWorkflowMCP',
      fileName: (format, entryName) => `${entryName}.js`,
      formats: ['cjs'],
    },
    rollupOptions: {
      external: [
        // Node.js built-ins with node: prefix
        'node:fs',
        'node:path',
        'node:os',
        'node:child_process',
        'node:util',
        'node:stream',
        'node:events',
        'node:crypto',
        'node:url',
        'node:querystring',
        'node:process',
        'node:assert',
        'node:net',
        'node:http',
        'node:buffer',
        'node:zlib',
        'node:tls',
        'node:http2',
        'node:dns',
        'node:async_hooks',
        'node:diagnostics_channel',
        'node:perf_hooks',
        'node:worker_threads',
        'node:console',
        'node:util/types',
        'node:sqlite',
        'timers/promises',
        'fs/promises',
        // Node.js built-ins without prefix
        'fs',
        'path',
        'os',
        'child_process',
        'util',
        'stream',
        'events',
        'crypto',
        'url',
        'querystring',
        'process',
        'assert',
        'net',
        'http',
        'buffer',
        'zlib',
        'tls',
        'http2',
        'dns',
        'async_hooks',
        'diagnostics_channel',
        'perf_hooks',
        'worker_threads',
        'console',
        // Dependencies that should remain external
        '@modelcontextprotocol/sdk',
        'fastmcp',
        'commander',
        'inquirer',
        'chalk',
        'marked',
        'yaml',
        'zod',
        'undici',
        'raw-body',
        'mcp-proxy',
      ],
      output: {
        globals: {
          '@modelcontextprotocol/sdk': 'MCPSdk',
        },
      },
    },
    target: 'node18',
    outDir: 'dist',
    emptyOutDir: true,
    sourcemap: true,
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
      '@/types': resolve(__dirname, 'src/types'),
      '@/utils': resolve(__dirname, 'src/utils'),
      '@/workflow': resolve(__dirname, 'src/workflow'),
      '@/config': resolve(__dirname, 'src/config'),
      '@/server': resolve(__dirname, 'src/server'),
      '@/cli': resolve(__dirname, 'src/cli'),
    },
  },
  define: {
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production'),
  },
});
